---
- hosts: localhost
  collections:
    - oracle.oci
  vars:
    json_report: ./report.json
  tasks:
    - name: Create a sample JSON file
      file: path="{{json_report}}" state=touch

    - name: Copy the json file structure in the file
      copy:
        content: "[{}]"
        dest: "{{json_report}}"

    - name: Adding set_fact into json
      oci_json_patch:
        src: "{{json_report}}"
        operations:
          - op: add
            path: "/0/about_me"
            value: {}
          - op: add
            path: "/0/about_me/name"
            value: "Jahidul Arafat"
        pretty: yes
        create: yes
