apiVersion: v1
kind: Service
metadata:
  name: travellist-app-service
spec:
  selector:
    app: travellist-app
  ports:
    - protocol: TCP
      port: 80  # The port you want to expose externally
      targetPort: 9000  # The port your app containers are listening on
  type: ClusterIP
