apiVersion: v1
kind: Service
metadata:
  name: travellist-nginx-service
spec:
  selector:
    app: travellist-nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort  # You can use a different service type if needed
