apiVersion: apps/v1
kind: Deployment
metadata:
  name: travellist-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travellist-nginx
  template:
    metadata:
      labels:
        app: travellist-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /var/www
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: travellist-nginx
spec:
  selector:
    app: travellist-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
