---
- hosts: localhost
  collections:
    - oracle.oci

  vars_prompt:
    - name: instance_id
      prompt: "Enter Instance ID [Check ./report.txt]: "
      private: no
  tasks:
    - name: Terminate the instance
      oci_compute_instance:
        id: "{{ instance_id }}"
        state: absent
    - debug:
        msg: "Instance {{instance_id}} is terminated"
