---
- name: Terminate the Public Load Balancer
  hosts: localhost
  collections:
    - oracle.oci

  vars_prompt:
    - name: loadbalancer_id
      prompt: "Enter Load Balancer ID:"
      default: "ocid1.loadbalancer.oc1.ap-mumbai-1.aaaaaaaa3tumo26trzdvsj7pp2jthfnvzg27lcjtszvw2uprzebcvrfejyeq"
      private: no

  tasks:
    # Task-01: Delete the Public Load Balancer
    - name: Deleting the Private Load Balancer
      oci_loadbalancer_load_balancer:
        load_balancer_id: "{{loadbalancer_id}}"
        state: absent
    - debug:
        msg: "LoadBalancer OCID: {{loadbalancer_id}} has been deleted"

