all:
  hosts:
    150.230.234.46:        #DevOps EX1
  children:
    webservers:
      hosts:
        129.154.230.31:     #DevOps EX2
        144.24.109.65:      #DevOps EX3
    dbservers:
      hosts:
        129.154.225.235:    #DevOps EX4
