# Use the official Nginx image
FROM nginx:1.25.4-alpine3.18

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your Nginx configuration file
COPY ./docker-compose/nginx /etc/nginx/conf.d/

# copy the webserver contents
COPY ./ /var/www

# Expose the Nginx port
EXPOSE 80

# Set the Nginx user to match the host user
#RUN sed -i 's/user  nginx;/user  www-data;/' /etc/nginx/conf.d/

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
